red-hat-storage/rhcephcompose

rhcephcompose/compose.py

Possibly a typo. I can't find any references to `os.mkdirs` in the Python 2 or 3 documentation.

Change `os.mkdirs` to `os.makedirs`

---

rhcephcompose/artifacts.py
rhcephcompose/build.py
rhcephcompose/compose.py

Adds a `chacra_ssl_verify` configuration option to specify a path to a certificate to verify. Other acceptable values:
- `True` (default): perform the usual verification using the system's CA certificate store.
- `False`: don't perform any verification of the Chacra server's SSL certificate. Prints many warnings.

Add SSL verification configuration for interacting with Chacra

---

.travis.yml

kobo does not support py3: https://bugzilla.redhat.com/1328199
Running on py3 when we know it's going to fail just wastes time.

.travis.yml: remove py3 support

---

rhcephcompose/__init__.py
rhcephcompose/artifacts.py
rhcephcompose/build.py
rhcephcompose/compose.py
rhcephcompose/comps.py

Centralize the logger code, so that we use a shared logger across the module.
Use a custom logger format string so log output is more user-friendly and readable.
It makes flake8 unhappy to have this code in `__init__.py` before those other imports, so eventually I should re-organize this.

centralize logging

---

rhcephcompose/compose.py

There were a couple of small changes needed in order to handle more than one distro (for example, "trusty" and "xenial").

multi-distro bug fixes

---

rhcephcompose/compose.py

Fixes the following error:
File "rhcephcompose/compose.py", line 86, in run
os.mkdir(self.output_dir)
File "rhcephcompose/compose.py", line 73, in output_dir
log.info('Using new compose dir: %s' % output_dir)
AttributeError: 'module' object has no attribute 'info'

compose.py: fix log import

---

rhcephcompose/log.py

Requests (or urllib3?) prints many messages like:
INFO: Starting new HTTPS connection (1): chacra.example.com
Silence these.

log.py: silence requests' INFO logging

---

.travis.yml

New builds in Travis are failing with this pytest-flake8 plugin, and I'm not sure of the root cause. Installing the package into the Travis virtualenv seems to fix it.

.travis.yml: install pytest-flake8 in virtualenv

---

rhcephcompose/main.py

Disables SSL certificate verification when communicating with chacra.

Add --insecure command line option

---

rhcephcompose/compose.py
rhcephcompose/tests/test_compose.py

Write a "-latest" symlink each time we generate a new compose.

compose: add "latest" symlink feature

---

rhcephcompose/compose.py

Whoops, meant to add this in ec0b7390d42e6fb9c970a65fb61a21b3aa461239, the commit that added this feature.

compose: call latest_symlink()

---

rhcephcompose/compose.py
rhcephcompose/main.py

For the automatic composes for QE, the sources repository is not necessary. Rather than doing the work and deleting it, this change would allow the job to skip composing it.

Add option to skip composing sources

---

.travis.yml

pytest-flake8 v0.6 and flake8 v3 seem to have broken py26 support. Install older versions when running the tests on Python 2.6.

travis.yml: pin flake8 on py26

---

rhcephcompose/artifacts.py
rhcephcompose/build.py
rhcephcompose/tests/test_artifacts.py

Prior to this change, we would blindly trust the files in the cache were good to use without validating the cached files' contents. This could cause issues when rhcephcompose crashed and left the cache in an invalid state, or some network interruption or other disk issue caused our cache files to exist with invalid contents.
When parsing the data for each build artifact, store the artifacts' sha512 checksum values from the chacra server, and validate that the checksums match our cached files. If they do not match, exit with an error.
The purpose of this change is to make it safer to trust the download operations and cache integrity.

verify cached files' checksums

---

rhcephcompose/artifacts.py
rhcephcompose/tests/test_artifacts.py

The first two commits in this PR improve the unit tests for the Artifacts classes to cover the `verify_checksum()` function.
The last commit optimizes repeated calls to `verify_checksum()` for large files. Prior to this PR, we would calculate the sha512 checksum of a cached file every time we used it. This was fast for small packages, but takes several seconds for large -dbg packages.
This change saves an in-memory set of cache files we've verified so the subsequent `verify_checksum()` calls are less expensive.

artifacts' cache checksum improvements

---

rhcephcompose/tests/test_artifacts.py

The py lib added the `write_binary()` method to LocalPath instances in py v1.4.24.
RH's internal rel-eng builds of python-py for el6 are v1.4.15.
Fall back to using the simpler `write()` method in order to support these older py lib versions.
RHEL 7 ships python-py 1.4.27 in the rhel-7-server-optional-rpms repo, so we can revert this change whenever we finally drop RHEL 6 support.

tests: handle old py versions

---

rhcephcompose/compose.py
rhcephcompose/main.py
rhcephcompose/tests/test_compose.py

Pungi supports four distinct compose types, which affect the name of the
compose output directory. Instead of appending a `.t` suffix before the
respin suffix, now `rhcephcompose` will use the following map:
`production` -> no suffix
`nightly` -> `.n`
`test` -> `.t` (default)
`ci` -> `.ci`

Add support for compose types

---

README.rst

Describe how rhcephcompose uses its local disk cache and the `XDG_CACHE_HOME` environment variable.

README: add cache docs

---

rhcephcompose/artifacts.py
rhcephcompose/build.py
rhcephcompose/tests/test_build.py

`name_version_re` is already supposed to match the beginning of the string, so use `re.match()`.
The purpose of this change is to clarify the intention of these property
methods and optimize the code.
For the `Build` class, add unit tests to verify that these properies are
correctly set.

build / artifacts: use re.match() rather than search()

---

rhcephcompose/tests/test_compose.py

Compatibility with pytest 2.3.5. This is what RH rel-eng ships in eng-rhel-6.

tests: pass tuple to pytest.mark.parameterize

---

rhcephcompose/artifacts.py

It's easy to accidentally write code that downloads artifacts to a
directory that doesn't yet exist. When that happens, download() will
quietly write the files to a *file* named by the "cache_dir" or
"dest_dir" arg, rather than writing those files into the respective
directories.
To guard against this in new code, sanity-check the directory args to
download() and ensure that they really are directories.

artifacts: sanity-check download() directory args

---

rhcephcompose/artifacts.py
rhcephcompose/build.py
rhcephcompose/compose.py
rhcephcompose/comps.py
rhcephcompose/tests/test_artifacts.py

**This change needs further work and testing before we merge this.**
With this change, rhcephcompose will place all of the debug packages into a separate "-debug" directory.
A new setting `include_dbg` toggles this behavior. (We'll want to disable `include_dbg` in Jenkins CI runs in order to save time and disk space).
TODO:
https://bugzilla.redhat.com/1375078

DNM: debug packages in composes

---

rhcephcompose/artifacts.py
rhcephcompose/compose.py
rhcephcompose/tests/test_artifacts.py
rhcephcompose/tests/test_compose.py

Prior to this change, we would dump all binary files into a single directory.
Build a set of all dbg binaries, and then generate a proper debian repo with metadata for this set. This allows users to install the packages with apt-get.

compose: create repository with dbg packages

---

setup.py

Fixes flake8 error E402: module level import not at top of file

setup.py: move imports to top of file

---

rhcephcompose/tests/test_compose.py
setup.py
travisci/install.sh
travisci/run.sh

The first commit updates the Python 2.6 tests so that we use the same version of py/pytest libs that are available in RH's rel-eng RHEL 6 environment.
The second commit fixes the test suite to pass on the older version of py 1.4.15 that is available.

fix tests for older libs in eng-rhel-6

---

rhcephcompose/tests/conftest.py
rhcephcompose/tests/test_compose.py
rhcephcompose/tests/test_comps.py
rhcephcompose/tests/test_main.py
rhcephcompose/tests/test_variants.py

Prior to this change:
- Every test file had its own copy-pasted `TESTS_DIR`/`FIXTURES_DIR`.
- `TestCompose` used a value (`self.conf`) across tests.
Refactor this to use pytest fixtures instead:
- Move `fixtures_dir` to a central pytest fixture in `conftest.py`, and reuse this across all tests that need it.
- Make `test_compose.py`'s old `self.conf` into a pytest fixture instead.  This makes it less likely that we will accidentally mutate `self.conf` during a test and affect other tests. It also eliminates hacks in `test_output_dir()` where we had to use `copy()` when we *did* need to mutate the value for each test parameter.

tests: use pytest fixtures

---

rhcephcompose/tests/test_main.py

Assert `main()`'s behavior, rather than simply testing that we don't raise.
Ensure that main's `--insecure` arg sets the `chacra_ssl_verify` config option as expected.

tests: better main tests

---

rhcephcompose/compose.py
rhcephcompose/tests/fixtures/basic.conf
rhcephcompose/tests/test_compose.py
rhcephcompose/tests/test_main.py

The `product_version` setting name comes from Distill. Let's stop using that, and use Pungi's `release_version` instead. The purpose of this change is to make our tool align more with rel-eng's standard tool for RPM composes.
For backwards compatibility, load `product_version` when `release_version` is not defined (in older configurations).

compose: product_version -> release_version

---

rhcephcompose/compose.py
rhcephcompose/tests/fixtures/basic.conf
rhcephcompose/tests/test_compose.py
rhcephcompose/tests/test_main.py

This will allow us to change the product name from "Ceph" to "RHCEPH" to match what we do with Pungi.

add release_short configuration option

---

rhcephcompose/compose.py
rhcephcompose/tests/fixtures/basic.conf
rhcephcompose/tests/test_compose.py
rhcephcompose/tests/test_main.py

Prior to this change, `symlink_latest()` would create a "latest" symlink for the exact release version eg. "2.3".
To have a latest "2" symlink, we had to set release_version to "2". This makes it harder to distinguish configurations and especially individual compose output directories from each other.
Determine the major version number and create that "latest" compose instead.
Update our test fixtures to use the "X.Y" version convention I expect us to use going forward.

compose: symlink latest major version

---

rhcephcompose/main.py
travisci/install.sh

Red Hat's eng-rhel-6 has python-requests-2.3.0-2.el6eng. Install this in our Travis CI py26 environment so we more closely replicate rel-eng's el6 environment.

travisci: use old eng-rhel-6 requests version

---

travisci/install.sh

There is a new pull request in progress to add Python 3 support to Kobo.
Use that version instead of the old/stale python-3-dev branch.
Install it in the Python 2 tests as well for more coverage.

travisci: install newer py3 kobo

---

travisci/install.sh

eng-rhel-6 currently has kobo 0.6.0.
Python 3 support is available as of kobo 0.7.0, so we don't need to install from Git any more.

travisci: update kobo versions

---

rhcephcompose/artifacts.py
rhcephcompose/tests/test_artifacts.py

Koji currently only supports md5 for checksums. Add a checksum_method
kwarg to the artifacts classes so we can use md5 to validate build
files.

artifacts: configurable checksums

---

rhcephcompose/artifacts.py

Prior to this change, when we called `download(cache_dir)`, we failed to dynamically create the cache directory if it did not already exist. We were calling `makedirs()` on a non-existant artifact object attribute, not the method argument.
The reason we did not hit this code path in rhcephcompose until now is that we have already called `makedirs` in the main `Compose` class, before we get to the individual `PackageArtifact` classes.
In fact, this error appears to be a bad copy-and-paste from the `Compose` class.

artifacts: fix cache_dir creation

---

rhcephcompose/artifacts.py

Add a new optional `session` kwarg to `download()`, so we can pass in a persistent requests.Session() object. This allows us to optimize a large set of artifact downloads.
If we don't set `session` in the caller, just initialize a fresh requests Session as before.
Note, no callers use this yet.

artifacts: support persistent requests session

---

rhcephcompose/compose.py

`builds` is a little vague. Rename it to `build_ids` to make it clearer that it's a list of build IDs, not a list of Build objects.

compose: rename "builds" variable

---

README.rst

Fix a bad copy-and-paste to point at the proper upstream URL for the Chacra project.

README: fix chacra URL

---

rhcephcompose/compose.py
rhcephcompose/gather/__init__.py
rhcephcompose/gather/chacra.py

Move "gather" logic out of the main Compose class and into a separate module.
This moves the "find and download" bits out of the main loops so we can eventually have more flexibility around how we add builds. It also adds flexibility for alternate gather methods (ie. Koji).

add rhcephcompose.gather module

---

setup.py

Add whitespace after class definition
Use raw string for regex

setup.py: fix two flake8 warnings

---

rhcephcompose/gather/chacra.py

If a build has no whitelisted binaries from our comps manifest, it probably means that we should remove it from the builds .txt list altogether.

gather: bail if a build has no whitelisted binaries

---

rhcephcompose/compose.py
rhcephcompose/gather/chacra.py

CPython closes this immediately, but there's nothing in the Python language
definition that says that the filehandle must be closed/garbage-collected.
Might as well close it here using the "with" statement.

implicitly close build list file handles

---

.travis.yml
README.rst
rhcephcompose/common_koji.py
rhcephcompose/compose.py
rhcephcompose/gather/koji.py
setup.py
travisci/install.sh

Support listing and downloading builds from Koji.
When "koji_profile" is set, rhcephcompose will use Koji as a build source instead of Chacra.

add koji support

---

rhcephcompose/compose.py

Instead of using the dangerous/difficult-to-read `while 1` condition, refactor this logic into two methods, so we can evaluate `os.path.isdir()` in the `while` condition.

compose: refactor _find_respin while loop

---

setup.py

Prior to this change, `python setup.py sdist` did not include the new subdirectories in our package here.

setup.py: use find_packages()

---

rhcephcompose/artifacts.py

Prior to this change, we would throw away the persistent requests session instead of using it. This meant that even if callers passed in a persistent requests session, we would just create a new one with `requests.get()`.
This is a fix for the feature introduced in 6567a1f37d475e98bb63512a723c6fdbcaef0027

artifacts: use requests session for download

---

setup.py

The latest versions of pytest (v4.1) require a list of strings here, not one single string.

setup.py: split args to pytest.main

---

travisci/install.sh

Red Hat's eng-rhel-6 has PyYAML-3.10-3.el6eng.1. Install this in our Travis CI py26 environment so we more closely replicate rel-eng's el6 environment.

travisci: use old eng-rhel-6 PyYAML version
